# Generated by Django 3.2.13 on 2023-11-02 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
